# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-09 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern_galery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternentry',
            name='added_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
